# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=vek

matrix:
  include:
    # NOTE(yoanlcq): Put these first because they supposedly take
    # more time to setup and easy to fail.
    - env: TARGET=asmjs-unknown-emscripten
    - env: TARGET=asmjs-unknown-emscripten
      rust: nightly
    - env: TARGET=wasm32-unknown-emscripten
    - env: TARGET=wasm32-unknown-emscripten
      rust: nightly

    # Linux
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-gnu
      rust: nightly
    #- env: TARGET=i686-unknown-linux-musl
    # NOTE(yoanlcq): AVOID_DOC_TESTS is a hack to work around
    # an existing issue (https://github.com/rust-lang/cargo/issues/4224)
    # related to serde_derive and prevents tests from compiling.
    - env: TARGET=x86_64-unknown-linux-gnu AVOID_DOC_TESTS=1
    - env: TARGET=x86_64-unknown-linux-gnu AVOID_DOC_TESTS=1
      rust: nightly
    #- env: TARGET=x86_64-unknown-linux-musl

    # Avoiding Mac machines because builds on them are sloooooow
    # Besides i686 and x86_64 are already tested on Linux and Windows.
    # OSX
    #- env: TARGET=i686-apple-darwin
    #  os: osx
    #- env: TARGET=x86_64-apple-darwin
    #  os: osx

    # *BSD
    #- env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
    #- env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    #- env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1

    # Other architectures
    - env: TARGET=arm-linux-androideabi
    - env: TARGET=arm-linux-androideabi
      rust: nightly
    - env: TARGET=armv7-linux-androideabi
    - env: TARGET=armv7-linux-androideabi
      rust: nightly
    - env: TARGET=aarch64-linux-android
    - env: TARGET=aarch64-linux-android
      rust: nightly
    # NOTE(yoanlcq): All of these platforms should be uncommented once
    # we reach 1.0
    #- env: TARGET=aarch64-unknown-linux-gnu
    #- env: TARGET=aarch64-unknown-linux-gnu
    #  rust: nightly
    #- env: TARGET=armv7-unknown-linux-gnueabihf
    #- env: TARGET=armv7-unknown-linux-gnueabihf
    #  rust: nightly
    #- env: TARGET=mips-unknown-linux-gnu
    #- env: TARGET=mips-unknown-linux-gnu
    #  rust: nightly
    #- env: TARGET=mips64-unknown-linux-gnuabi64
    #- env: TARGET=mips64-unknown-linux-gnuabi64
    #  rust: nightly
    #- env: TARGET=mips64el-unknown-linux-gnuabi64
    #- env: TARGET=mips64el-unknown-linux-gnuabi64
    #  rust: nightly
    #- env: TARGET=mipsel-unknown-linux-gnu
    #- env: TARGET=mipsel-unknown-linux-gnu
    #  rust: nightly
    #- env: TARGET=powerpc-unknown-linux-gnu
    #- env: TARGET=powerpc-unknown-linux-gnu
    #  rust: nightly
    #- env: TARGET=powerpc64-unknown-linux-gnu
    #- env: TARGET=powerpc64-unknown-linux-gnu
    #  rust: nightly
    #- env: TARGET=powerpc64le-unknown-linux-gnu
    #- env: TARGET=powerpc64le-unknown-linux-gnu
    #  rust: nightly
    #- env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    #- env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    #  rust: nightly

before_install: set -e

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
