[package]
authors = ["Yoan Lecoq <yoanlecoq.io@gmail.com>"]
description = "Generic but efficient SIMD vector+matrix library for game engines, with focus on intent and the small bits that make you happier as a user."
documentation = "https://docs.rs/vek"
keywords = ["vector", "matrix", "simd"]
categories = [ "algorithms", "data-structures", "no-std", "science" ]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/yoanlcq/vek"
name = "vek"
version = "0.2.0" # remember to update html_root_url in src/lib.rs
build = "build.rs"

[badges]
travis-ci = { repository = "yoanlcq/vek" }
appveyor  = { repository = "yoanlcq/vek" }

[features]
default = ["repr_simd", "repr_align", "serde", "f32", "u8"]
repr_align = []
repr_simd = []
f32 = []
f64 = []
i8 = []
u8 = []
i16 = []
u16 = []
i32 = []
u32 = []
i64 = []
u64 = []
i128 = []
u128 = []
isize = []
usize = []
itypes = [ "i8", "i16", "i32", "i64" ]
utypes = [ "u8", "u16", "u32", "u64" ]
ftypes = [ "f32", "f64" ]

[build-dependencies]
rustc_version = "0.2.1"

[dependencies]
clippy = {version = "*", optional = true}
#num-traits = "0.1.39"
#num-integer = "0.1.34"
num-bigint = { version = "0.1.40", optional = true }
serde = { version = "1.0.10", optional = true, features = ["derive"] }
# XXX HACK around AppVeyor
serde_derive = { version = "1.0.10", optional = true }
fix = { version = "0.1.0", optional = true }
fpa = { version = "0.1.0", optional = true }

[target.'cfg(any(target_arch="x86", target_arch="x86_64"))'.dependencies]
x86intrin = { version = "0.4.2", optional = true }
