[package]
authors = ["Yoan Lecoq <yoanlecoq.io@gmail.com>"]
description = "Generic but efficient SIMD vector+matrix library for game engines, with focus on intent and the small bits that make you happier as a user."
documentation = "https://docs.rs/vek"
keywords = ["vector", "matrix", "simd"]
categories = [ "algorithms", "data-structures", "no-std", "science" ]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/yoanlcq/vek"
name = "vek"
version = "0.2.2" # remember to update html_root_url in src/lib.rs
build = "build.rs"
exclude = [
    "previous_work/*",
    "ci/*",
    "appveyor.yml",
    ".travis.yml",
]

[badges]
travis-ci = { repository = "yoanlcq/vek" }
appveyor  = { repository = "yoanlcq/vek" }

[features]
default = ["serde", "repr_simd", "repr_align", "vec2", "vec3", "vec8", "vec16", "vec32", "vec64", "xyzw", "xyz", "xy", "rgba", "rgb", "extent3", "extent2", "uvw", "uv", "mat2", "mat3", "mat4"]
# TODO limited features only to decrease compile times
# default = ["serde", "repr_simd", "repr_align", "vec2", "vec3", "vec4", "xy", "xyz", "xyzw", "mat3", "mat4", "extent2", "extent3"]
repr_align = []
repr_simd = []
vec2 = []
vec3 = []
vec4 = []
vec8 = []
vec16 = []
vec32 = []
vec64 = []
xyzw = []
xyz = []
xy = []
rgba = []
rgb = []
extent3 = []
extent2 = []
uvw = []
uv = []
mat2 = ["vec2"]
mat3 = ["vec3"]
mat4 = ["vec4"]

[build-dependencies]
rustc_version = "0.2.1"

[dependencies]
clippy = { version = "0.0.148", optional = true }
num-traits = "0.1.39"
num-integer = "0.1.34"
num-bigint = { version = "0.1.40", optional = true }
serde = { version = "1.0.10", optional = true, features = ["derive"] }
fix = { version = "0.1.0", optional = true }
fpa = { version = "0.1.0", optional = true }

[target.'cfg(any(target_arch="x86", target_arch="x86_64"))'.dependencies]
x86intrin = { version = "0.4.2", optional = true }
